<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.548">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Jacob Adams">

<title>Homework 6</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="hw6_files/libs/clipboard/clipboard.min.js"></script>
<script src="hw6_files/libs/quarto-html/quarto.js"></script>
<script src="hw6_files/libs/quarto-html/popper.min.js"></script>
<script src="hw6_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="hw6_files/libs/quarto-html/anchor.min.js"></script>
<link href="hw6_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="hw6_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="hw6_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="hw6_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="hw6_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body>

<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Homework 6</h1>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p><span style="background-color: yellow;">Jacob Adams</span> </p>
            </div>
    </div>
      
    
      
    </div>
    
  
  </header><div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#section" id="toc-section" class="nav-link active" data-scroll-target="#section"><br><br><br><br></a></li>
  <li><a href="#question-1" id="toc-question-1" class="nav-link" data-scroll-target="#question-1">Question 1</a></li>
  </ul>
</nav>
</div>
<main class="content quarto-banner-title-block" id="quarto-document-content">





<div class="callout callout-style-default callout-important callout-titled" style="font-size: 0.8em;">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>Please read the instructions carefully before submitting your assignment.</p>
<ol type="1">
<li>This assignment requires you to only upload a <code>PDF</code> file on Canvas</li>
<li>Don’t collapse any code cells before submitting.</li>
<li>Remember to make sure all your code output is rendered properly before uploading your submission.</li>
</ol>
<p>⚠️ Please add your name to the author information in the frontmatter before submitting your assignment ⚠️</p>
</div>
</div>
<p>In this assignment, we will perform various tasks involving principal component analysis (PCA), principal component regression, and dimensionality reduction.</p>
<p>We will need the following packages:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>packages <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">"tibble"</span>,</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"dplyr"</span>, </span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"readr"</span>, </span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"tidyr"</span>, </span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"purrr"</span>, </span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  <span class="st">"broom"</span>,</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  <span class="st">"magrittr"</span>,</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>  <span class="st">"corrplot"</span>,</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>  <span class="st">"car"</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="co"># renv::install(packages)</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="fu">sapply</span>(packages, require, <span class="at">character.only=</span>T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="section" class="level2">
<h2 class="anchored" data-anchor-id="section"><br><br><br><br></h2>
</section>
<section id="question-1" class="level2">
<h2 class="anchored" data-anchor-id="question-1">Question 1</h2>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
70 points
</div>
</div>
<div class="callout-body-container callout-body">
<p>Principal component anlaysis and variable selection</p>
</div>
</div>
<section id="points-1" class="level6">
<h6 class="anchored" data-anchor-id="points-1">1.1 (5 points)</h6>
<p>The <code>data</code> folder contains a <code>spending.csv</code> dataset which is an illustrative sample of monthly spending data for a group of <span class="math inline">\(5000\)</span> people across a variety of categories. The response variable, <code>income</code>, is their monthly income, and objective is to predict the <code>income</code> for a an individual based on their spending patterns.</p>
<p>Read the data file as a tibble in R. Preprocess the data such that:</p>
<ol type="1">
<li>the variables are of the right data type, e.g., categorical variables are encoded as factors</li>
<li>all column names to lower case for consistency</li>
<li>Any observations with missing values are dropped</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>path <span class="ot">&lt;-</span> <span class="st">"data/spending.csv"</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(path)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 5000 Columns: 40
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
dbl (40): accessories, accommodation, alcohol, audio_equipment, beverages, b...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename_all</span>(tolower) <span class="sc">%&gt;%</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>()</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">as_tibble</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<hr>
</section>
<section id="points-2" class="level6">
<h6 class="anchored" data-anchor-id="points-2">1.2 (5 points)</h6>
<p>Visualize the correlation between the variables using the <code>corrplot()</code> function. What do you observe? What does this mean for the model?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>corrlelation_matrix <span class="ot">&lt;-</span> <span class="fu">cor</span>(df)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">corrplot</span>(corrlelation_matrix, <span class="at">method =</span> <span class="st">"color"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="hw6_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><em>There is a large amount of collinearity between about half of all the predictor variables. As a result, this is very troublesome for the model, since collinearity often leads to inconsistent models.</em></p>
<hr>
</section>
<section id="points-3" class="level6">
<h6 class="anchored" data-anchor-id="points-3">1.3 (5 points)</h6>
<p>Run a linear regression model to predict the <code>income</code> variable using the remaining predictors. Interpret the coefficients and summarize your results.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>lm_fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(income <span class="sc">~</span>., <span class="at">data =</span> df)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = income ~ ., data = df)

Residuals:
    Min      1Q  Median      3Q     Max 
-8.6875 -1.6569  0.0427  1.6633  9.5623 

Coefficients:
                       Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)           -0.077509   0.121730  -0.637 0.524330    
accessories            0.299876   0.031786   9.434  &lt; 2e-16 ***
accommodation          0.113632   0.031262   3.635 0.000281 ***
alcohol               -0.005958   0.033266  -0.179 0.857873    
audio_equipment        0.602004   0.033483  17.979  &lt; 2e-16 ***
beverages              0.043335   0.034111   1.270 0.204000    
books                  0.070530   0.033238   2.122 0.033892 *  
cameras                0.461827   0.033572  13.756  &lt; 2e-16 ***
car_rentals            0.124875   0.032809   3.806 0.000143 ***
clothing               0.504228   0.026055  19.352  &lt; 2e-16 ***
coffee_shops           0.048839   0.034909   1.399 0.161864    
dairy_products         0.024548   0.032715   0.750 0.453082    
desktops               0.391673   0.033393  11.729  &lt; 2e-16 ***
electronics            1.079627   0.030035  35.946  &lt; 2e-16 ***
fast_food              0.077531   0.033014   2.348 0.018893 *  
food_delivery         -0.004903   0.034257  -0.143 0.886188    
fruits                 0.059089   0.033321   1.773 0.076237 .  
groceries              0.077694   0.031601   2.459 0.013981 *  
gym_memberships        0.141168   0.033410   4.225 2.43e-05 ***
jewelry                0.213726   0.032834   6.509 8.30e-11 ***
laptops                0.594328   0.032548  18.260  &lt; 2e-16 ***
magazines              0.080762   0.033694   2.397 0.016571 *  
meat                   0.081262   0.032367   2.511 0.012083 *  
movies                 0.110296   0.033326   3.310 0.000941 ***
music                  0.159925   0.033398   4.788 1.73e-06 ***
outdoor_activities     0.087846   0.032356   2.715 0.006651 ** 
public_transportation  0.061138   0.033022   1.851 0.064169 .  
restaurant_meals       0.066129   0.033225   1.990 0.046611 *  
seafood                0.061318   0.033786   1.815 0.069596 .  
shoes                  0.463185   0.029613  15.641  &lt; 2e-16 ***
smartphones            0.780150   0.031538  24.737  &lt; 2e-16 ***
snacks                 0.007464   0.033229   0.225 0.822290    
software               0.408500   0.034102  11.979  &lt; 2e-16 ***
sports_equipment       0.033328   0.033969   0.981 0.326574    
streaming_services     0.150614   0.031902   4.721 2.41e-06 ***
tablets                0.637266   0.033133  19.234  &lt; 2e-16 ***
travel                 0.129161   0.031457   4.106 4.09e-05 ***
vegetables            -0.066111   0.033162  -1.994 0.046257 *  
video_games            0.863309   0.031392  27.501  &lt; 2e-16 ***
watches                0.145853   0.033467   4.358 1.34e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.434 on 4960 degrees of freedom
Multiple R-squared:  0.9999,    Adjusted R-squared:  0.9999 
F-statistic: 1.834e+06 on 39 and 4960 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>##Interpretation of coefficientients: Accessories: Each unit increase in spending on accessories leads to an increase of 0.299876 in the response to income.</p>
<p>Accommodation: Each unit increase in spending on accommodation leads to an increase of 0.113632 in the response to income.</p>
<p>Alcohol: Spending on alcohol does not significantly affect the response to income.</p>
<p>Audio Equipment: Each unit increase in spending on audio equipment leads to an increase of 0.602004 in the response to income.</p>
<p>Beverages: Spending on beverages does not significantly affect the response to income.</p>
<p>Books: Each unit increase in spending on books leads to an increase of 0.070530 in the response to income.</p>
<p>Cameras: Each unit increase in spending on cameras leads to an increase of 0.461827 in the response to income.</p>
<p>Car Rentals: Each unit increase in spending on car rentals leads to an increase of 0.124875 in the response to income.</p>
<p>Clothing: Each unit increase in spending on clothing leads to an increase of 0.504228 in the response to income.</p>
<p>Coffee Shops: Spending on coffee shops does not significantly affect the response to income.</p>
<p>Dairy Products: Spending on dairy products does not significantly affect the response to income.</p>
<p>Desktops: Each unit increase in spending on desktops leads to an increase of 0.391673 in the response to income.</p>
<p>Electronics: Each unit increase in spending on electronics leads to an increase of 1.079627 in the response to income.</p>
<p>Fast Food: Each unit increase in spending on fast food leads to an increase of 0.077531 in the response to income.</p>
<p>Food Delivery: Spending on food delivery does not significantly affect the response to income.</p>
<p>Fruits: Spending on fruits does not significantly affect the response to income.</p>
<p>Groceries: Each unit increase in spending on groceries leads to an increase of 0.077694 in the response to income.</p>
<p>Gym Memberships: Each unit increase in spending on gym memberships leads to an increase of 0.141168 in the response to income.</p>
<p>Jewelry: Each unit increase in spending on jewelry leads to an increase of 0.213726 in the response to income.</p>
<p>Laptops: Each unit increase in spending on laptops leads to an increase of 0.594328 in the response to income.</p>
<p>Magazines: Each unit increase in spending on magazines leads to an increase of 0.080762 in the response to income.</p>
<p>Meat: Each unit increase in spending on meat leads to an increase of 0.081262 in the response to income.</p>
<p>Movies: Each unit increase in spending on movies leads to an increase of 0.110296 in the response to income.</p>
<p>Music: Each unit increase in spending on music leads to an increase of 0.159925 in the response to income.</p>
<p>Outdoor Activities: Each unit increase in spending on outdoor activities leads to an increase of 0.087846 in the response to income.</p>
<p>Public Transportation: Spending on public transportation does not significantly affect the response to income.</p>
<p>Restaurant Meals: Spending on restaurant meals does not significantly affect the response to income.</p>
<p>Seafood: Spending on seafood does not significantly affect the response to income.</p>
<p>Shoes: Each unit increase in spending on shoes leads to an increase of 0.463185 in the response to income.</p>
<p>Smartphones: Each unit increase in spending on smartphones leads to an increase of 0.780150 in the response to income.</p>
<p>Snacks: Spending on snacks does not significantly affect the response to income.</p>
<p>Software: Each unit increase in spending on software leads to an increase of 0.408500 in the response to income.</p>
<p>Sports Equipment: Spending on sports equipment does not significantly affect the response to income.</p>
<p>Streaming Services: Each unit increase in spending on streaming services leads to an increase of 0.150614 in the response to income.</p>
<p>Tablets: Each unit increase in spending on tablets leads to an increase of 0.637266 in the response to income.</p>
<p>Travel: Each unit increase in spending on travel leads to an increase of 0.129161 in the response to income.</p>
<p>Vegetables: Spending on vegetables does not significantly affect the response to income.</p>
<p>Video Games: Each unit increase in spending on video games leads to an increase of 0.863309 in the response to income.</p>
<p>Watches: Each unit increase in spending on watches leads to an increase of 0.145853 in the response to income.</p>
<p>Non-significant predictors (p-value &gt; 0.05):</p>
<p>Alcohol Beverages Coffee Shops Dairy Products Food Delivery Fruits Public Transportation Seafood Snacks Sports Equipment —</p>
</section>
<section id="points-4" class="level6">
<h6 class="anchored" data-anchor-id="points-4">1.3 (5 points)</h6>
<p>Diagnose the model using the vif function. What do you observe? What does this mean for the model?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">vif</span>(lm_fit))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          accessories         accommodation               alcohol 
            152.06821             681.15504             387.23376 
      audio_equipment             beverages                 books 
           1755.56441             914.69186             192.91781 
              cameras           car_rentals              clothing 
            785.43147             423.55906             282.25143 
         coffee_shops        dairy_products              desktops 
            425.39644            2336.74847             776.75697 
          electronics             fast_food         food_delivery 
           3927.16511            1519.85171             921.68162 
               fruits             groceries       gym_memberships 
           1550.05678            3136.80325             438.30224 
              jewelry               laptops             magazines 
             72.38215            1658.76990             198.53619 
                 meat                movies                 music 
           2284.43676             437.28082             437.03990 
   outdoor_activities public_transportation      restaurant_meals 
            411.17302             427.77815            1540.26240 
              seafood                 shoes           smartphones 
           1594.08027             233.33301            2772.27822 
               snacks              software      sports_equipment 
            868.24282             810.28919             201.00255 
   streaming_services               tablets                travel 
            709.25592            1718.78339             690.69616 
           vegetables           video_games               watches 
           1536.40686            2745.64421              75.56457 </code></pre>
</div>
</div>
<p><em>According to the rules of variance inflation factor, any values of “vif” above 5 are considered to have a high degree of multi-collinearity. Thus, we can see this model has an enormous amount of collinearity which will lead to an inneffective model.</em></p>
<hr>
</section>
<section id="points-5" class="level6">
<h6 class="anchored" data-anchor-id="points-5">1.4 (5 points)</h6>
<p>Perform PCA using the <code>princomp</code> function in R. Print the summary of the PCA object.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>pca <span class="ot">&lt;-</span> <span class="fu">princomp</span>(df, <span class="at">cor =</span> <span class="cn">TRUE</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(pca)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Importance of components:
                          Comp.1    Comp.2    Comp.3    Comp.4       Comp.5
Standard deviation     3.6250565 3.4480375 3.1501541 2.2298341 0.1125697797
Proportion of Variance 0.3285259 0.2972241 0.2480868 0.1243040 0.0003167989
Cumulative Proportion  0.3285259 0.6257499 0.8738367 0.9981407 0.9984574993
                             Comp.6      Comp.7       Comp.8       Comp.9
Standard deviation     0.0960777376 0.070831618 0.0691545366 0.0670347877
Proportion of Variance 0.0002307733 0.000125428 0.0001195587 0.0001123416
Cumulative Proportion  0.9986882726 0.998813701 0.9989332593 0.9990456008
                            Comp.10      Comp.11      Comp.12      Comp.13
Standard deviation     0.0653221903 5.099557e-02 4.981058e-02 4.762384e-02
Proportion of Variance 0.0001066747 6.501371e-05 6.202734e-05 5.670076e-05
Cumulative Proportion  0.9991522756 9.992173e-01 9.992793e-01 9.993360e-01
                            Comp.14      Comp.15      Comp.16      Comp.17
Standard deviation     4.698663e-02 4.611215e-02 4.590277e-02 4.552849e-02
Proportion of Variance 5.519359e-05 5.315825e-05 5.267662e-05 5.182109e-05
Cumulative Proportion  9.993912e-01 9.994444e-01 9.994970e-01 9.995489e-01
                            Comp.18      Comp.19      Comp.20      Comp.21
Standard deviation     4.516755e-02 3.944182e-02 3.586495e-02 0.0350545840
Proportion of Variance 5.100269e-05 3.889143e-05 3.215737e-05 0.0000307206
Cumulative Proportion  9.995999e-01 9.996388e-01 9.996709e-01 0.9997016390
                            Comp.22      Comp.23      Comp.24      Comp.25
Standard deviation     3.460923e-02 3.435492e-02 3.298824e-02 3.240375e-02
Proportion of Variance 2.994497e-05 2.950651e-05 2.720561e-05 2.625007e-05
Cumulative Proportion  9.997316e-01 9.997611e-01 9.997883e-01 9.998145e-01
                            Comp.26      Comp.27     Comp.28      Comp.29
Standard deviation     3.157795e-02 2.977572e-02 0.025086252 2.460209e-02
Proportion of Variance 2.492918e-05 2.216484e-05 0.000015733 1.513158e-05
Cumulative Proportion  9.998395e-01 9.998616e-01 0.999877373 9.998925e-01
                            Comp.30      Comp.31      Comp.32      Comp.33
Standard deviation     2.426620e-02 2.374610e-02 2.334392e-02 2.283050e-02
Proportion of Variance 1.472121e-05 1.409693e-05 1.362347e-05 1.303079e-05
Cumulative Proportion  9.999072e-01 9.999213e-01 9.999349e-01 9.999480e-01
                            Comp.34      Comp.35      Comp.36      Comp.37
Standard deviation     2.119155e-02 1.983574e-02 1.937935e-02 1.742907e-02
Proportion of Variance 1.122705e-05 9.836418e-06 9.388978e-06 7.594316e-06
Cumulative Proportion  9.999592e-01 9.999690e-01 9.999784e-01 9.999860e-01
                            Comp.38      Comp.39      Comp.40
Standard deviation     1.677847e-02 1.476855e-02 7.708148e-03
Proportion of Variance 7.037927e-06 5.452751e-06 1.485389e-06
Cumulative Proportion  9.999931e-01 9.999985e-01 1.000000e+00</code></pre>
</div>
</div>
<hr>
</section>
<section id="points-6" class="level6">
<h6 class="anchored" data-anchor-id="points-6">1.5 (5 points)</h6>
<p>Make a screeplot of the proportion of variance explained by each principal component. How many principal components would you choose to keep? Why?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">screeplot</span>(pca, <span class="at">type =</span> <span class="st">"l"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="hw6_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><em>I would keep 4 principal components based off of the screeplot. This is because only 4 components seem to explain the high degree of variance before it levels off.</em></p>
</section>
<section id="points-7" class="level6">
<h6 class="anchored" data-anchor-id="points-7">1.6 (5 points)</h6>
<p>By setting any factor loadings below <span class="math inline">\(0.2\)</span> to <span class="math inline">\(0\)</span>, summarize the factor loadings for the principal components that you chose to keep.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>loadings <span class="ot">&lt;-</span> pca<span class="sc">$</span>loadings </span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>clean_loading <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(pca<span class="sc">$</span>loadings[, <span class="dv">1</span><span class="sc">:</span><span class="dv">40</span>] <span class="sc">&lt;</span> <span class="fl">0.2</span>, <span class="dv">0</span>, <span class="fu">round</span>(pca<span class="sc">$</span>loadings[, <span class="dv">1</span><span class="sc">:</span><span class="dv">40</span>], <span class="dv">2</span>)) <span class="sc">%&gt;%</span> <span class="fu">as.data.frame</span>()</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(clean_loading)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Visualize the factor loadings.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>clean_loading <span class="sc">%&gt;%</span> <span class="fu">as.matrix</span>() <span class="sc">%&gt;%</span> <span class="fu">t</span>() <span class="sc">%&gt;%</span> <span class="fu">corrplot</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="hw6_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<hr>
</section>
<section id="points-8" class="level6">
<h6 class="anchored" data-anchor-id="points-8">1.7 (15 points)</h6>
<p>Based on the factor loadings, what do you think the principal components represent?</p>
<p><em>Based off the corrplot above I would keep components 1 and 2. These principal components represent a strong correlation between the variables and response variable that may be present in the data.</em></p>
<p>Provide an interpreation for each principal component you chose to keep.</p>
<p><em>Choosing to keep the principal components 1 and 2. We see in component one that alcohol, beverages, coffe_shop, dairy_products, fast_food, food_delivery, fruits, and groceries, meat, restaurant_meals, seafood, snacks, and vegetables all seem to be valid predictors. In component two we see accommodation, audio_equipment, books, car_rentals, gym_memberships, magazines, movies, music, outdoor_activities, public_transportation, sports_equipment, streaming_services, and travel seem to be valid predictors as well. The other components have a stronger correlation, but far less predictors. In the context of this data set, we should probably choose the larger models.</em></p>
<hr>
</section>
<section id="points-9" class="level6">
<h6 class="anchored" data-anchor-id="points-9">1.8 (10 points)</h6>
<p>Create a new data frame with the original response variable <code>income</code> and the principal components you chose to keep. Call this data frame <code>df_pca</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>Z <span class="ot">&lt;-</span> <span class="fu">predict</span>(pca, df) </span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>df_pca <span class="ot">&lt;-</span> Z <span class="sc">%&gt;%</span> as_tibble <span class="sc">%&gt;%</span> <span class="fu">select</span>(Comp<span class="fl">.1</span>, Comp<span class="fl">.2</span>) <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">income =</span> df<span class="sc">$</span>income)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="points-10" class="level6">
<h6 class="anchored" data-anchor-id="points-10">1.9 (10 points)</h6>
<p>Fit a regression model to predict the <code>income</code> variable using the principal components you chose to keep. Interpret the coefficients and summarize your results.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>lm_pca_fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(income <span class="sc">~</span>., <span class="at">data =</span> df_pca)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_pca_fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = income ~ ., data = df_pca)

Residuals:
    Min      1Q  Median      3Q     Max 
-584.10 -239.08    1.87  236.97  611.89 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  628.178      4.019 156.286   &lt;2e-16 ***
Comp.1        17.324      1.109  15.625   &lt;2e-16 ***
Comp.2        -1.682      1.166  -1.443    0.149    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 284.2 on 4997 degrees of freedom
Multiple R-squared:  0.04696,   Adjusted R-squared:  0.04658 
F-statistic: 123.1 on 2 and 4997 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Interpretation:</p>
<p>Comp.1: For every one unit increase in component one variables, there is a 17.324 increase in income. Comp.2: For every one unit increase in component two variables, there is a 1.682 decrease in income</p>
<p>Compare the results of the regression model in 1.3 and 1.9. What do you observe? What does this mean for the model?</p>
<hr>
</section>
<section id="points-11" class="level6">
<h6 class="anchored" data-anchor-id="points-11">1.10 (10 points)</h6>
<p>Based on your interpretation of the principal components from Question 1.7, provide an interpretation of the regression model in Question 1.9.</p>
<p><em>Examining the model we can see there is a high degree of error in the model. This may be because of a previous error where I decided to take more predictors over highly correlated components with less predictors. Component one is much more effective in predicting the income compared to component two. For example, it is a significant predictor where component two is not. Overall, it is still a better model than the original regression model.</em></p>
<hr>
<div class="hidden" data-unless-format="pdf">
<div style="page-break-after: always;"></div>
</div>
<p><br><br><br><br> <br><br><br><br> —</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Session Information
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Print your <code>R</code> session information using the following command</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sessionInfo</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>R version 4.3.1 (2023-06-16 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 11 x64 (build 22631)

Matrix products: default


locale:
[1] LC_COLLATE=English_United States.utf8 
[2] LC_CTYPE=English_United States.utf8   
[3] LC_MONETARY=English_United States.utf8
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

time zone: America/New_York
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] car_3.1-2      carData_3.0-5  corrplot_0.92  magrittr_2.0.3 broom_1.0.5   
 [6] purrr_1.0.2    tidyr_1.3.1    readr_2.1.5    dplyr_1.1.4    tibble_3.2.1  

loaded via a namespace (and not attached):
 [1] bit_4.0.5         jsonlite_1.8.7    crayon_1.5.2      compiler_4.3.1   
 [5] tidyselect_1.2.0  parallel_4.3.1    yaml_2.3.7        fastmap_1.1.1    
 [9] R6_2.5.1          generics_0.1.3    knitr_1.43        htmlwidgets_1.6.2
[13] backports_1.4.1   pillar_1.9.0      tzdb_0.4.0        rlang_1.1.1      
[17] utf8_1.2.3        xfun_0.40         bit64_4.0.5       cli_3.6.1        
[21] withr_2.5.0       digest_0.6.33     vroom_1.6.3       rstudioapi_0.15.0
[25] hms_1.1.3         lifecycle_1.0.3   vctrs_0.6.5       evaluate_0.21    
[29] glue_1.6.2        codetools_0.2-19  abind_1.4-5       fansi_1.0.4      
[33] rmarkdown_2.24    tools_4.3.1       pkgconfig_2.0.3   htmltools_0.5.6  </code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>